export const ACTIONS = {
    ADD_USER: 'ADD_USER',
    SET_USERS: 'SET_USERS', 
    LOGIN_USER: 'LOGIN_USER',
    LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',
    LOGIN_USER_COMPLETE: 'LOGIN_USER_COMPLETE',
}